apiVersion: v1
kind: PersistentVolume
metadata:
  name: zkpv1
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/zkpv1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zkpvc1
    
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: zkpv1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: akpv1
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/akpv1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akpvc1

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: akpv1

