apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apachekafka.component.zkdeploy: sri-zk-dplmnt
  name: sri-zookeeper-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      apachekafka.component.zkdeploy: sri-zk-dplmnt
  template:
    metadata:
      labels:
        apachekafka.component.zkdeploy: sri-zk-dplmnt
    spec:
      volumes:
      - name: zk-data
        persistentVolumeClaim:
          claimName: zkpvc1
      - name: zk-server-props
        configMap:
          name: sri-zk-cm
      containers:
      - image: docker.io/dockersri83/alpineapachekafka:v1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: zk-data
          mountPath: /data
        - name: zk-server-props
          mountPath: /app/kafka_2.13-3.7.0/config/zookeeper.properties
          subPath: zookeeper.properties
        name: sri-zookeeper
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        env:
        - name: KAFKA_HEAP_OPTS
          value: "-Xms128M -Xmx128M"
        - name: TZ
          value: Asia/Kolkata
#        command: [ "sleep" ]
#        args: [ "infinity" ]
        command: [ "/bin/sh" ]
        args: [ "/app/kafka_2.13-3.7.0/bin/zookeeper-server-start.sh", "/app/kafka_2.13-3.7.0/config/zookeeper.properties"]
        ports:
        - containerPort: 2181
          name: zk2181
